---
name: cfsummit

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: cfsummit
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  persistent_disk: 65535
  jobs:
  - name: cfsummit
    release: cfsummit
    properties: {}
  - name: redis-server
    release: cfsummit
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  version: 0.12.3
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
- name: cfsummit
  version: 1.0.0
  url: git+https://github.com/starkandwayne/cfsummit-boshrelease
